### ISSUE TITLE
\begin{frame}[plain]

### ISSUE THREAD

**Issue by ghost** [elauksap/beamerthemepolimi#1]
I think the default is to make the title slide like that

```
	\begin{frame}[plain]
		\maketitle
	\end{frame}
```

at least this is how it is setup up by TexStudio. But if you do this it produces an empty slide, followed by the title slide with the content of the second slide. That is, the title slide is empty. The second slide, which should contain contents, is superimposed over the background of the title slide.

If you instead follow the demo and declare the title slide like this.
```
	\begin{frame}
		\maketitle
	\end{frame}
```
it will work as expected

**Comment by pcafrica** [comment]
Hi raffam,

I've just committed some modifications that fix the issue.

Thanks for reporting and for using the theme!
